### ISSUE TITLE
Done and Delete buttons seems incorrect on ios device

### ISSUE THREAD

**Issue by irfansimsar** [irfansimsar/es6-todo-app#2]
![simulator screen shot - iphone 8 plus - 2018-02-18 at 12 19 34](https://user-images.githubusercontent.com/3313222/36350244-459505f8-14a6-11e8-8417-7f711bcf6dac.png)

**Comment by serdaraglamis** [comment]
@irfansimsar Also they are looking bad in chrome :(

**Comment by irfansimsar** [comment]
@serdar-aglamis-wcar the design changed completely, so this problem disappeared
